// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0

import { createHash } from "node:crypto";
import type { StaffPrincipal } from "../../../../../shared/auth/staff-principal";
import type { DatabaseSession, TransactionRunner } from "../../../../../shared/database/transaction";
import type { AgenticRepository } from "../../repositories/interfaces/agentic.repository";
import type { AgenticFileScanner } from "../../security/agentic-file-scanner";
import type { AgenticFileStorage } from "../../storage/agentic-file-storage";
import type { AgentTask } from "../../../domain/entities/agent-task";
import type { AgenticFilePreview, AgenticIntakeFile } from "../../../domain/entities/agentic-file";
import { transitionAgenticIntakeFile } from "../../../domain/services/agentic-file-rules";
import { parseBoundedAgenticFile } from "../../../infrastructure/parsing/bounded-agentic-file.parser";
import { AgenticApplicationError } from "../agentic-application.error";
import type { AgenticFilePreviewDto, AgenticFileService, AgenticFileUploadRequest, ApproveAgenticFilePreviewRequest } from "../interfaces/agentic-file.service";

type FileRepository = Pick<AgenticRepository, "createIntakeFile" | "findIntakeFile" | "transitionIntakeFile" | "appendFilePreview" | "findFilePreview" | "findFileApprovalByIdempotency" | "approveFilePreview" | "findTaskById" | "appendAudit" | "appendProvenance">;

export class AgenticFileServiceImpl implements AgenticFileService {
  constructor(private readonly repository: FileRepository, private readonly storage: AgenticFileStorage, private readonly scanner: AgenticFileScanner, private readonly transactions: TransactionRunner, private readonly generateId: () => string, private readonly now: () => string) {}
  async upload(input: AgenticFileUploadRequest, principal: StaffPrincipal): Promise<{ readonly file: AgenticIntakeFile }> {
    admin(principal); const format = formatFor(input); safe(input.content); const at = this.now(); const id = this.generateId();
    const file: AgenticIntakeFile = { id, objectKey: `agentic-intake/${id}`, originalFilename: input.originalFilename.trim(), format, mediaType: input.mediaType, byteSize: input.content.byteLength, payloadDigest: sha(input.content), status: "uploaded", createdBy: principal.subject, version: 1, createdAt: at, updatedAt: at };
    try { await this.transactions.run(async (s) => { await this.repository.createIntakeFile(s, file); await this.audit(s, principal, file.id, "agentic_file.upload", at); }); await this.storage.put(file.objectKey, input.content, file.mediaType); } catch { await this.storage.delete(file.objectKey).catch(() => undefined); fail("FILE_UPLOAD_FAILED", "File upload could not be recorded safely"); }
    return { file };
  }
  async scanAndPreview(fileId: string, principal: StaffPrincipal): Promise<AgenticFilePreviewDto> {
    admin(principal); const file = await this.transactions.runReadOnly((s) => this.file(s, fileId)); if (file.status === "previewed") return this.preview(file.id); if (file.status !== "uploaded") fail("FILE_STATE_INVALID", "File cannot be scanned");
    const scanning = transitionAgenticIntakeFile(file, "scanning", this.now()); if (!await this.transactions.run((s) => this.repository.transitionIntakeFile(s, scanning, file.version))) return this.replay(fileId);
    try {
      if ((await this.scanner.scan(await this.storage.open(file.objectKey))).status !== "clean") return this.rejectClaim(scanning, principal);
      const clean = transitionAgenticIntakeFile(scanning, "clean", this.now()); if (!await this.transactions.run((s) => this.repository.transitionIntakeFile(s, clean, scanning.version))) return this.replay(fileId);
      const parsed = parseBoundedAgenticFile(clean.format, await bytes(await this.storage.open(file.objectKey))); const preview = createPreview(clean, parsed, this.generateId(), this.now()); const previewed = transitionAgenticIntakeFile(clean, "previewed", this.now());
      const settled = await this.transactions.run(async (s) => { await this.repository.appendFilePreview(s, preview); return this.repository.transitionIntakeFile(s, previewed, clean.version); }); if (!settled) return this.replay(fileId); return mapPreview(preview, clean.format);
    } catch (error) { await this.rejectClaim(scanning, principal); if (error instanceof AgenticApplicationError) throw error; fail("FILE_CONTENT_INVALID", "File content is not safe for intake"); }
  }
  async reject(id: string, version: number, principal: StaffPrincipal): Promise<AgenticIntakeFile> { return this.terminal(id, version, "rejected", principal); }
  async delete(id: string, version: number, principal: StaffPrincipal): Promise<AgenticIntakeFile> { return this.terminal(id, version, "deleted", principal); }
  async approvePreview(input: ApproveAgenticFilePreviewRequest, principal: StaffPrincipal): Promise<AgentTask> {
    admin(principal); return this.transactions.run(async (s) => { const file = await this.file(s, input.fileId); if (file.status === "approved") { const replay = await this.repository.findFileApprovalByIdempotency(s, input.idempotencyKey); if (!replay) fail("FILE_STATE_INVALID", "File preview is not approvable"); const task = await this.repository.findTaskById(s, replay.taskId); if (!task) fail("FILE_APPROVAL_CONFLICT", "Approved task was not found"); return task; } if (file.version !== input.expectedFileVersion) fail("STALE_VERSION", "File version is stale"); if (file.status !== "previewed") fail("FILE_STATE_INVALID", "File preview is not approvable"); const preview = await this.repository.findFilePreview(s, file.id, input.previewVersion); if (!preview || preview.payloadDigest !== input.previewPayloadDigest) fail("PREVIEW_DIGEST_MISMATCH", "Preview payload digest has changed");
      const at = this.now(); const task: AgentTask = { id: this.generateId(), state: "draft", createdBy: principal.subject, goal: `Review intake file: ${file.originalFilename}`, instructions: "Review the approved file preview.", version: 1, createdAt: at, updatedAt: at }; const result = await this.repository.approveFilePreview(s, { id: this.generateId(), fileId: file.id, previewVersion: preview.previewVersion, previewDigest: preview.previewDigest, expectedFileVersion: input.expectedFileVersion, previewPayloadDigest: input.previewPayloadDigest, task, idempotencyKey: input.idempotencyKey, approvedBy: principal.subject, approvedAt: at }); const stored = result.status === "created" ? task : await this.repository.findTaskById(s, result.taskId); if (!stored) fail("FILE_APPROVAL_CONFLICT", "Approved task was not found");
      if (result.status === "created") { await this.repository.appendProvenance(s, { id: this.generateId(), taskId: stored.id, sourceType: "agentic_intake_file", sourceId: file.id, sourceDigest: file.payloadDigest, sourceVersion: file.version, classification: "internal", recordedBy: principal.subject, recordedAt: at }); await this.repository.appendProvenance(s, { id: this.generateId(), taskId: stored.id, sourceType: "agentic_file_preview", sourceId: preview.id, sourceDigest: preview.previewDigest, sourceVersion: preview.previewVersion, classification: "internal", recordedBy: principal.subject, recordedAt: at }); await this.audit(s, principal, file.id, "agentic_file.approve", at); } return stored;
    });
  }
  private async replay(id: string): Promise<AgenticFilePreviewDto> { const file = await this.transactions.runReadOnly((s) => this.file(s, id)); if (file.status !== "previewed") fail("FILE_PROCESSING", "File processing is in progress"); return this.preview(id); }
  private async preview(id: string): Promise<AgenticFilePreviewDto> { return this.transactions.runReadOnly(async (s) => { const [file, preview] = await Promise.all([this.file(s, id), this.repository.findFilePreview(s, id, 1)]); if (!preview) fail("FILE_PREVIEW_NOT_FOUND", "File preview was not found"); return mapPreview(preview, file.format); }); }
  private async rejectClaim(file: AgenticIntakeFile, principal: StaffPrincipal): Promise<never> { const rejected = transitionAgenticIntakeFile(file, "rejected", this.now()); await this.transactions.run(async (s) => { await this.repository.transitionIntakeFile(s, rejected, file.version); await this.audit(s, principal, file.id, "agentic_file.reject", rejected.updatedAt); }); await this.storage.delete(file.objectKey).catch(() => undefined); fail("FILE_CONTENT_INVALID", "File content is not safe for intake"); }
  private async terminal(id: string, expected: number, target: "rejected" | "deleted", principal: StaffPrincipal): Promise<AgenticIntakeFile> { admin(principal); const file = await this.transactions.runReadOnly((s) => this.file(s, id)); if (file.version !== expected) fail("STALE_VERSION", "File version is stale"); const next = transitionAgenticIntakeFile(file, target, this.now()); if (!await this.transactions.run((s) => this.repository.transitionIntakeFile(s, next, file.version))) fail("STALE_VERSION", "File version is stale"); await this.storage.delete(file.objectKey).catch(() => undefined); return next; }
  private async file(s: DatabaseSession, id: string): Promise<AgenticIntakeFile> { const file = await this.repository.findIntakeFile(s, id); if (!file) fail("FILE_NOT_FOUND", "File was not found"); return file; }
  private async audit(s: DatabaseSession, p: StaffPrincipal, id: string, action: string, at: string): Promise<void> { await this.repository.appendAudit(s, { id: this.generateId(), actorId: p.subject, actorType: "staff", action, resourceType: "agentic_intake_file", resourceId: id, outcome: "allowed", correlationId: id, occurredAt: at }); }
}
function formatFor(input: AgenticFileUploadRequest): "csv" | "txt" { if (!input.originalFilename.trim() || input.originalFilename.length > 255) fail("FILE_TYPE_NOT_ALLOWED", "File name is invalid"); if (input.mediaType === "text/csv") return "csv"; if (input.mediaType === "text/plain") return "txt"; fail("FILE_TYPE_NOT_ALLOWED", "Only CSV and plain-text file intake is allowed"); }
function safe(content: Buffer): void { if (!content.byteLength || content.byteLength > 2 * 1024 * 1024 || content.includes(0)) fail("FILE_CONTENT_INVALID", "File content is not safe for intake"); try { new TextDecoder("utf-8", { fatal: true }).decode(content); } catch { fail("FILE_CONTENT_INVALID", "File content is not safe for intake"); } }
function createPreview(file: AgenticIntakeFile, parsed: { readonly rowCount: number; readonly columnCount: number; readonly samples: readonly string[] }, id: string, at: string): AgenticFilePreview { const summary = { rowCount: parsed.rowCount, columnCount: parsed.columnCount, samples: [...parsed.samples], sourceReferences: parsed.samples.map((_, i) => ({ fileId: file.id, line: i + 1 })) }; return { id, fileId: file.id, previewVersion: 1, parserVersion: "bounded-csv-txt-v1", payloadDigest: file.payloadDigest, previewDigest: sha(JSON.stringify(summary)), summary, createdAt: at }; }
function mapPreview(preview: AgenticFilePreview, format: "csv" | "txt"): AgenticFilePreviewDto { const s = preview.summary as { rowCount: number; columnCount: number; samples: readonly string[]; sourceReferences: readonly { fileId: string; line: number; column?: number }[] }; return { fileId: preview.fileId, previewVersion: preview.previewVersion, parserVersion: preview.parserVersion, payloadDigest: preview.payloadDigest, previewDigest: preview.previewDigest, format, rowCount: s.rowCount, columnCount: s.columnCount, samples: [...s.samples], sourceReferences: s.sourceReferences.map((r) => ({ ...r })) }; }
async function bytes(stream: NodeJS.ReadableStream): Promise<Buffer> { const chunks: Buffer[] = []; for await (const chunk of stream) chunks.push(Buffer.from(chunk)); return Buffer.concat(chunks); }
function sha(input: string | Uint8Array): string { return createHash("sha256").update(input).digest("hex"); }
function admin(p: StaffPrincipal): void { if (!p.roles.includes("agentic_governance_admin") && !p.roles.includes("administrator")) fail("FORBIDDEN", "Governance administrator role is required"); }
function fail(code: string, message: string): never { throw new AgenticApplicationError(code, message); }
