# SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
# SPDX-License-Identifier: Apache-2.0

packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - esbuild

allowBuilds:
  esbuild: true
