// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0

import { FormEvent, useMemo, useState } from "react";
import { CommerceSummary } from "../components/commerce-summary";
import { OperationsSummary } from "../components/operations-summary";
import { ProductPerformance } from "../components/product-performance";
import { useDashboard } from "../hooks/use-dashboard";
import type { DashboardApi } from "../api/dashboard-api";
import type { DashboardRangeInput } from "../types/dashboard.types";

const DAY_MS=86400000;
export function DashboardPage({api}:{readonly api:DashboardApi}){const initial=useMemo(defaultRange,[]);const [range,setRange]=useState<DashboardRangeInput>(initial);const [draft,setDraft]=useState<DashboardRangeInput>(initial);const [rangeError,setRangeError]=useState<string>();const {data,error,loading,reload}=useDashboard(api,range);const apply=(event:FormEvent)=>{event.preventDefault();const days=(Date.parse(`${draft.end}T00:00:00.000Z`)-Date.parse(`${draft.start}T00:00:00.000Z`))/DAY_MS;if(!Number.isFinite(days)||days<1||days>366){setRangeError("Choose a range from 1 to 366 days.");return;}setRangeError(undefined);setRange(draft);};const stale=data!==undefined&&Date.now()-Date.parse(data.refreshedAt)>60000;return <section className="catalogWorkspace operationsWorkspace dashboardWorkspace"><header className="workspaceHeader splitHeader"><div><p className="sectionKicker">Executive reporting</p><h1>Commerce dashboard</h1><p>Aggregate, PII-free metrics in Asia/Ho_Chi_Minh.</p></div></header><form className="filterBar" onSubmit={apply}><label><span>Start date</span><input aria-label="Start date" type="date" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></label><label><span>End date</span><input aria-label="End date" type="date" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></label><button className="primaryButton" type="submit">Apply range</button></form>{rangeError?<div className="pageState" role="alert">{rangeError}</div>:null}{loading&&!data?<div className="pageState" role="status">Loading dashboard metrics…</div>:error?<div className="pageState" role="alert"><p>{error}</p><button className="secondaryButton" type="button" onClick={reload}>Retry</button></div>:data?<><p className="subtleText">Range {data.range.start} to {data.range.end}; refreshed {new Date(data.refreshedAt).toLocaleString("vi-VN")}</p>{stale?<div className="pageState" role="alert">Metrics are older than 60 seconds.</div>:null}<CommerceSummary commerce={data.commerce}/><OperationsSummary operations={data.operations}/><ProductPerformance products={data.products}/><section className="dashboardGrid" aria-label="Customer aggregates"><article className="detailCard"><h2>Registered customers</h2><strong>{data.customers.totalRegisteredCustomers}</strong></article><article className="detailCard"><h2>Repeat customers</h2><strong>{data.customers.repeatCustomers}</strong></article></section></>:null}</section>;}
function defaultRange():DashboardRangeInput{const end=new Date(Date.now()).toISOString().slice(0,10);const start=new Date(Date.now()-30*DAY_MS).toISOString().slice(0,10);return{start,end};}
