// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0
import type { TransactionRunner } from "../../../../../shared/database/transaction";
import type { CustomerOperationsReader } from "../../../../customer";
import type { CustomerOrderOperationsReader } from "../../../../order";
import { transitionTicket } from "../../../domain/services/support-rules";
import type { SupportTicket } from "../../../domain/entities/support-ticket";
import { mapEvent, mapMessage, mapTicket } from "../../mappers/support.mapper";
import type { SupportContext } from "../../dtos/support.dto";
import type { SupportRepository } from "../../repositories/interfaces/support.repository";
import { SupportApplicationError } from "../support-application.error";
import type { SupportOperationsSummaryReader, SupportServiceContract } from "../interfaces/support.service";

export class SupportService implements SupportServiceContract, SupportOperationsSummaryReader {
  constructor(private readonly repository:SupportRepository,private readonly customers:CustomerOperationsReader,private readonly orders:CustomerOrderOperationsReader,private readonly transactions:TransactionRunner,private readonly generateId:()=>string,private readonly now:()=>string) {}
  async list(query:{page:number;pageSize:number},context:SupportContext) { this.allowQueue(context); const result=await this.transactions.runReadOnly(s=>this.repository.list(s,query)); return {...result,items:result.items.map(mapTicket),page:query.page,pageSize:query.pageSize,totalPages:Math.max(1,Math.ceil(result.totalItems/query.pageSize))}; }
  async create(input:{customerId:string;orderId?:string;subject:string;description:string;priority:SupportTicket["priority"]},context:SupportContext) { this.allowCreate(context); if(await this.customers.get(input.customerId)===undefined) throw new SupportApplicationError("CUSTOMER_NOT_FOUND","Customer not found"); if(input.orderId!==undefined && await this.orders.getOwned(input.customerId,input.orderId)===undefined) throw new SupportApplicationError("ORDER_NOT_FOUND","Order not found"); return this.transactions.run(async s=>{const now=this.now();const ticket:SupportTicket={id:this.generateId(),...input,status:"new",version:1,createdById:context.actorId,slaPausedSeconds:0,slaStoppedSeconds:0,createdAt:now,updatedAt:now};await this.repository.create(s,ticket);await this.audit(s,ticket,context,"support.ticket.created",now);return mapTicket(ticket);}); }
  async detail(id:string,context:SupportContext) { return this.transactions.runReadOnly(async s=>{const ticket=await this.require(s,id);this.allowRead(context,ticket);const customer=await this.customers.getSupportContext(ticket.customerId);if(customer===undefined)throw new SupportApplicationError("CUSTOMER_NOT_FOUND","Customer not found");const [messages,events,order]=await Promise.all([this.repository.listMessages(s,id),this.repository.listEvents(s,id),ticket.orderId===undefined?undefined:this.orders.getOwned(ticket.customerId,ticket.orderId)]);return {ticket:mapTicket(ticket),context:{customer,...(order===undefined?{}:{order})},messages:messages.map(mapMessage),events:events.map(mapEvent)};}); }
  async claim(id:string,version:number,context:SupportContext) { this.allowOperate(context); return this.transactions.run(async s=>{const ticket=await this.require(s,id,true);if(ticket.assigneeId!==undefined&&ticket.assigneeId!==context.actorId)throw new SupportApplicationError("ALREADY_CLAIMED","Ticket is already claimed");if(ticket.assigneeId===context.actorId)return mapTicket(ticket);if(ticket.version!==version)throw new SupportApplicationError("STALE_VERSION","Ticket version is stale");const updated={...transitionTicket(ticket,ticket.status==="new"?"assigned":ticket.status,context.actorId,this.now()),assigneeId:context.actorId};if(!await this.repository.update(s,updated,version))throw new SupportApplicationError("STALE_VERSION","Ticket version is stale");await this.repository.appendEvent(s,{id:this.generateId(),ticketId:id,actorId:context.actorId,fromStatus:ticket.status,toStatus:updated.status,source:"manual",idempotencyKey:`claim:${id}:${version}`,occurredAt:updated.updatedAt});await this.audit(s,updated,context,"support.ticket.claimed",updated.updatedAt);return mapTicket(updated);}); }
  async transition(id:string,input:{status:SupportTicket["status"];version:number;idempotencyKey:string},context:SupportContext) { this.allowOperate(context); return this.transactions.run(async s=>{const prior=await this.repository.findEventByKey(s,input.idempotencyKey);if(prior!==undefined){const ticket=await this.require(s,id);return mapTicket(ticket);}const ticket=await this.require(s,id,true);if(ticket.version!==input.version)throw new SupportApplicationError("STALE_VERSION","Ticket version is stale");const updated=transitionTicket(ticket,input.status,context.actorId,this.now());if(!await this.repository.update(s,updated,input.version))throw new SupportApplicationError("STALE_VERSION","Ticket version is stale");await this.repository.appendEvent(s,{id:this.generateId(),ticketId:id,actorId:context.actorId,fromStatus:ticket.status,toStatus:updated.status,source:"manual",idempotencyKey:input.idempotencyKey,occurredAt:updated.updatedAt});await this.audit(s,updated,context,"support.ticket.transitioned",updated.updatedAt);return mapTicket(updated);}); }
  async appendMessage(id:string,body:string,context:SupportContext) { this.allowOperate(context);return this.transactions.run(async s=>{const ticket=await this.require(s,id);const message={id:this.generateId(),ticketId:id,authorId:context.actorId,body,createdAt:this.now()};await this.repository.appendMessage(s,message);await this.audit(s,ticket,context,"support.ticket.message.appended",message.createdAt);return mapMessage(message);}); }
  async summarize(asOf:string,start:string,end:string){return this.transactions.runReadOnly(s=>this.repository.countSummary(s,asOf,start,end));}
  private allowCreate(c:SupportContext){if(!c.roles.some(r=>r==="administrator"||r==="crm_operator"||r==="support_operator"))throw new SupportApplicationError("FORBIDDEN","Insufficient permissions");}
  private allowQueue(c:SupportContext){if(!c.roles.some(r=>r==="administrator"||r==="support_operator"))throw new SupportApplicationError("FORBIDDEN","Insufficient permissions");}
  private allowOperate(c:SupportContext){this.allowQueue(c);}
  private allowRead(c:SupportContext,t:SupportTicket){if(c.roles.includes("administrator")||c.roles.includes("support_operator")||(c.roles.includes("crm_operator")&&t.createdById===c.actorId))return;throw new SupportApplicationError("FORBIDDEN","Insufficient permissions");}
  private async require(s:Parameters<SupportRepository["find"]>[0],id:string,lock=false){const t=await this.repository.find(s,id,lock);if(t===undefined)throw new SupportApplicationError("TICKET_NOT_FOUND","Ticket not found");return t;}
  private async audit(s:Parameters<SupportRepository["appendAudit"]>[0],t:SupportTicket,c:SupportContext,action:string,at:string){await this.repository.appendAudit(s,{id:this.generateId(),ticketId:t.id,actorId:c.actorId,action,resourceId:t.id,correlationId:c.correlationId,metadata:{},occurredAt:at});}
}
