// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0

export type AgenticTaskState = "draft" | "ready" | "received" | "planning" | "awaiting_plan_approval" | "dispatching" | "department_analysis" | "quality_review" | "collaboration" | "executive_synthesis" | "awaiting_human_approval" | "retrying" | "partially_completed" | "failed" | "canceled" | "completed";
export interface AgenticTaskFilter { readonly page: number; readonly pageSize: number; readonly state?: AgenticTaskState; readonly createdBy?: string; readonly createdFrom?: string; readonly createdTo?: string }
export interface AgenticTaskSummary { readonly id: string; readonly state: AgenticTaskState; readonly createdBy: string; readonly goal: string; readonly version: number; readonly createdAt: string; readonly updatedAt: string }
export interface AgenticTaskPage { readonly items: readonly AgenticTaskSummary[]; readonly totalItems: number; readonly refreshedAt: string }
export interface AgenticTaskOverview { readonly counts: Readonly<Record<"running" | "waiting" | "failed" | "completed" | "canceled", number>>; readonly pendingApprovals: number; readonly settledCostMicros: number; readonly refreshedAt: string }
export interface AgenticTaskIntake { readonly mode: "store_health_review" | "advanced"; readonly goal: string; readonly instructions: string; readonly deadline?: string; readonly reviewWindow?: { readonly start: string; readonly end: string } }
export interface AgenticTaskDetail { readonly task: AgenticTaskSummary; readonly subtasks: readonly { readonly id?: string; readonly agentKind: string; readonly title: string }[]; readonly dependencies: readonly { readonly from: string; readonly to: string }[] }
export interface AgenticFile { readonly id: string; readonly originalFilename: string; readonly format: "csv" | "txt"; readonly mediaType: "text/csv" | "text/plain"; readonly byteSize: number; readonly payloadDigest: string; readonly status: "uploaded" | "scanning" | "clean" | "previewed" | "approved" | "rejected" | "deleted"; readonly createdBy: string; readonly version: number; readonly scannedAt?: string; readonly approvedAt?: string; readonly rejectedAt?: string; readonly deletedAt?: string; readonly createdAt: string; readonly updatedAt: string }
export interface AgenticFileGovernancePreview { readonly coordinator: "ai_ceo"; readonly eligibleDepartments: readonly ("catalog" | "inventory" | "order" | "finance" | "crm" | "support")[]; readonly allowedTools: readonly string[]; readonly dataClasses: readonly string[]; readonly riskSignals: readonly string[]; readonly dependencyStatus: "planned_after_task_start"; readonly configurationRevisionId: string; readonly configurationVersion: number }
export interface AgenticFilePreview { readonly fileId: string; readonly fileVersion: number; readonly previewVersion: number; readonly parserVersion: string; readonly payloadDigest: string; readonly previewDigest: string; readonly format: "csv" | "txt"; readonly rowCount: number; readonly columnCount: number; readonly invalidRows: number; readonly samples: readonly string[]; readonly sourceReferences: readonly { readonly fileId: string; readonly line: number; readonly column?: number }[]; readonly governance: AgenticFileGovernancePreview }
export interface AgenticFileApproval { readonly expectedFileVersion: number; readonly previewVersion: number; readonly previewPayloadDigest: string }
export interface AgenticTimelineEvent { readonly id: string; readonly kind: string; readonly state: string; readonly occurredAt: string; readonly branchId?: string; readonly reasonCode?: string }
export interface AgenticExecutionBranch { readonly id: string; readonly owner: string; readonly state: string; readonly dependencies: readonly string[]; readonly toolNames: readonly string[]; readonly dataClasses: readonly string[] }
export interface AgenticExecutiveReport { readonly completionState: "complete" | "partial" | "quality_escalated" | "canceled"; readonly summary: string; readonly conclusions: readonly { readonly code: string; readonly statement: string; readonly provenanceIds: readonly string[] }[]; readonly risks: readonly { readonly code: string; readonly statement: string; readonly severity: "low" | "medium" | "high"; readonly provenanceIds: readonly string[] }[]; readonly recommendedActions: readonly { readonly code: string; readonly statement: string; readonly requiresHumanApproval: boolean; readonly provenanceIds: readonly string[] }[]; readonly conflicts: readonly { readonly code: string; readonly statement: string; readonly provenanceIds: readonly string[] }[]; readonly unavailableBranches: readonly { readonly subtaskId: string; readonly reasonCode: string }[] }
export interface AgenticTaskOperations { readonly task: { readonly id: string; readonly goal: string; readonly state: string; readonly version: number }; readonly workflow?: { readonly id: string; readonly state: string; readonly stage: string; readonly version: number; readonly updatedAt: string }; readonly timeline: readonly AgenticTimelineEvent[]; readonly branches: readonly AgenticExecutionBranch[]; readonly costs: { readonly reservedMicros: number; readonly settledMicros: number }; readonly approvals: readonly { readonly id: string; readonly state: string; readonly expiresAt: string; readonly version: number }[]; readonly provenance: readonly { readonly id: string; readonly sourceType: string; readonly sourceId: string; readonly classification: string }[]; readonly report?: AgenticExecutiveReport; readonly refreshedAt: string }
export type AgenticApprovalState = "pending" | "approved" | "rejected" | "revision_requested";
export interface AgenticApproval { readonly id: string; readonly state: AgenticApprovalState; readonly requesterId: string; readonly approverScope: "tool_invocation" | "emergency_revocation" | "governance_configuration" | "workflow_execution"; readonly action: string; readonly resourceType: string; readonly resourceId: string; readonly parametersDigest: string; readonly taskId?: string; readonly policyVersion: number; readonly workflowVersion?: number; readonly configurationRevisionId: string; readonly expiresAt: string; readonly version: number; readonly createdAt: string; readonly decidedBy?: string; readonly decisionReason?: string; readonly decidedAt?: string }
export interface AgenticApprovalPage { readonly items: readonly AgenticApproval[]; readonly totalItems: number }
export interface AgenticApprovalDetail { readonly approval: AgenticApproval; readonly payloadDigest?: string; readonly risk: { readonly level: "low" | "medium" | "high"; readonly basis: string }; readonly expectedEffect: string; readonly sources: readonly { readonly sourceType: string; readonly sourceId: string; readonly sourceDigest: string }[]; readonly refreshedAt: string }
export interface AgenticApprovalDecision { readonly expectedVersion: number; readonly decision: "approved" | "rejected" | "revision_requested"; readonly reason: string }
export type AgentKind = "ai_ceo" | "catalog" | "inventory" | "order" | "finance" | "crm" | "support";
export interface AgenticEmployeeSummary { readonly kind: AgentKind; readonly department: string; readonly active: boolean }
export interface AgenticEmployeeDetail { readonly kind: AgentKind; readonly department: string; readonly governance: { readonly active: boolean; readonly revoked: boolean; readonly configurationVersion: number }; readonly models: { readonly primary: string; readonly fallbacks: readonly string[] }; readonly tools: readonly { readonly name: string; readonly version: number; readonly dataScope: string }[]; readonly budgets: { readonly taskCostMicros: number; readonly dailyCostMicros: number; readonly monthlyCostMicros: number }; readonly executionHealth: { readonly state: "available" | "revoked" | "degraded" | "unknown"; readonly basis: string; readonly freshness: string }; readonly recentRuns: readonly { readonly taskId: string; readonly state: string; readonly settledCostMicros: number; readonly completedAt?: string }[] }
export interface AgenticAuditFilter { readonly page: number; readonly pageSize: number; readonly actorId?: string; readonly action?: string; readonly outcome?: "allowed" | "denied" | "failed"; readonly resourceType?: string; readonly occurredFrom?: string; readonly occurredTo?: string }
export interface AgenticAuditEvent { readonly id: string; readonly actorId: string; readonly actorType: "staff" | "agent" | "system"; readonly taskId?: string; readonly action: string; readonly resourceType: string; readonly resourceId: string; readonly outcome: "allowed" | "denied" | "failed"; readonly policyVersion?: number; readonly modelVersion?: number; readonly toolVersion?: number; readonly correlationId: string; readonly causationId?: string; readonly parametersDigest?: string; readonly attempt?: number; readonly durationMs?: number; readonly resultDigest?: string; readonly errorCode?: string; readonly occurredAt: string }
export interface AgenticAuditPage { readonly items: readonly AgenticAuditEvent[]; readonly totalItems: number; readonly refreshedAt: string }
