// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0
import type { MigrationBuilder } from "node-pg-migrate";
export function up(pgm: MigrationBuilder): void {
  pgm.createTable("carts", { id: { type: "uuid", primaryKey: true }, guest_session_id: { type: "uuid", references: "guest_sessions", onDelete: "RESTRICT" }, customer_id: { type: "uuid", references: "customers", onDelete: "RESTRICT" }, status: { type: "text", notNull: true, default: "active" }, version: { type: "integer", notNull: true, default: 1 }, expires_at: { type: "timestamptz", notNull: true }, created_at: { type: "timestamptz", notNull: true, default: pgm.func("current_timestamp") }, updated_at: { type: "timestamptz", notNull: true, default: pgm.func("current_timestamp") } });
  pgm.addConstraint("carts", "carts_exactly_one_owner_check", { check: "(guest_session_id IS NOT NULL)::int + (customer_id IS NOT NULL)::int = 1" });
  pgm.addConstraint("carts", "carts_status_check", { check: "status IN ('active', 'superseded', 'checkout_ready')" }); pgm.addConstraint("carts", "carts_version_check", { check: "version > 0" });
  pgm.sql("CREATE UNIQUE INDEX carts_one_active_guest ON carts (guest_session_id) WHERE status = 'active'"); pgm.sql("CREATE UNIQUE INDEX carts_one_active_customer ON carts (customer_id) WHERE status = 'active'");
  pgm.createTable("cart_items", { id: { type: "uuid", primaryKey: true }, cart_id: { type: "uuid", notNull: true, references: "carts", onDelete: "CASCADE" }, variant_id: { type: "uuid", notNull: true, references: "product_variants", onDelete: "RESTRICT" }, quantity: { type: "integer", notNull: true }, last_validated_unit_price_vnd: { type: "bigint", notNull: true }, created_at: { type: "timestamptz", notNull: true, default: pgm.func("current_timestamp") }, updated_at: { type: "timestamptz", notNull: true, default: pgm.func("current_timestamp") } });
  pgm.addConstraint("cart_items", "cart_items_cart_variant_unique", { unique: ["cart_id", "variant_id"] }); pgm.addConstraint("cart_items", "cart_items_quantity_check", { check: "quantity > 0" }); pgm.addConstraint("cart_items", "cart_items_price_check", { check: "last_validated_unit_price_vnd >= 0 AND last_validated_unit_price_vnd <= 9007199254740991" });
  pgm.createTable("cart_resolution_requests", { id: { type: "uuid", primaryKey: true }, customer_id: { type: "uuid", notNull: true, references: "customers", onDelete: "RESTRICT" }, idempotency_key: { type: "varchar(128)", notNull: true }, request_fingerprint: { type: "char(64)", notNull: true }, action: { type: "text", notNull: true }, guest_cart_id: { type: "uuid", references: "carts", onDelete: "RESTRICT" }, saved_cart_id: { type: "uuid", references: "carts", onDelete: "RESTRICT" }, resulting_cart_id: { type: "uuid", references: "carts", onDelete: "RESTRICT" }, created_at: { type: "timestamptz", notNull: true, default: pgm.func("current_timestamp") } });
  pgm.addConstraint("cart_resolution_requests", "cart_resolution_requests_customer_key_unique", { unique: ["customer_id", "idempotency_key"] }); pgm.addConstraint("cart_resolution_requests", "cart_resolution_requests_action_check", { check: "action IN ('keep_guest', 'keep_saved', 'merge')" }); pgm.addConstraint("cart_resolution_requests", "cart_resolution_requests_fingerprint_check", { check: "request_fingerprint ~ '^[a-f0-9]{64}$'" });
}
export function down(pgm: MigrationBuilder): void { pgm.dropTable("cart_resolution_requests"); pgm.dropTable("cart_items"); pgm.dropTable("carts"); }
