// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0

import { ImageUp, Star, Trash2 } from "lucide-react";
import { useState, type ChangeEvent, type FormEvent } from "react";
import type { CatalogApi } from "../api/catalog-api";
import { useProductMedia } from "../hooks/use-product-media";
import type { ProductMedia } from "../types/catalog.types";

const acceptedTypes = new Set(["image/jpeg", "image/png", "image/webp", "image/avif"]);
export function MediaManager({ api, productId, maximumBytes = 10 * 1024 * 1024 }: { readonly api: CatalogApi; readonly productId: string; readonly maximumBytes?: number }) {
  const manager = useProductMedia(api, productId); const [file, setFile] = useState<File>(); const [altText, setAltText] = useState(""); const [error, setError] = useState<string>(); const [deleteTarget, setDeleteTarget] = useState<ProductMedia>(); const [orders, setOrders] = useState<Readonly<Record<string, string>>>({}); const [altTexts, setAltTexts] = useState<Readonly<Record<string, string>>>({});
  function chooseFile(event: ChangeEvent<HTMLInputElement>) { const selected = event.target.files?.[0]; setError(undefined); if (!selected) return; if (!acceptedTypes.has(selected.type)) { setFile(undefined); setError("Use a JPEG, PNG, WebP, or AVIF image."); return; } if (selected.size > maximumBytes) { setFile(undefined); setError(`Image must be no larger than ${maximumBytes} bytes.`); return; } setFile(selected); }
  async function upload(event: FormEvent) { event.preventDefault(); if (!file) { setError("Choose a supported product image."); return; } if (!altText.trim()) { setError("Alt text is required."); return; } setError(undefined); await manager.upload({ file, altText: altText.trim(), sortOrder: manager.media.length, isPrimary: manager.media.length === 0 }); }
  async function saveOrder(media: ProductMedia) { const sortOrder = Number(orders[media.id] ?? media.sortOrder); if (!Number.isSafeInteger(sortOrder) || sortOrder < 0) { setError("Sort order must be a non-negative integer."); return; } await manager.update(media.id, { sortOrder }); }
  async function saveAltText(media: ProductMedia) { const value = (altTexts[media.id] ?? media.altText).trim(); if (!value) { setError("Alt text is required."); return; } await manager.update(media.id, { altText: value }); }
  return <div className="editorPanel"><form className="mediaUpload" onSubmit={(event) => void upload(event)}><label>Product image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={chooseFile} /></label><label>Image alt text<input value={altText} onChange={(event) => setAltText(event.target.value)} /></label><button className="primaryButton" type="submit"><ImageUp size={16} /> Upload image</button>{manager.progress !== undefined && <span>Upload {manager.progress}%</span>}{error && <p className="formError">{error}</p>}{manager.notice && <p className="formError">{manager.notice}</p>}</form>{manager.media.length === 0 ? <div className="emptyState">No media uploaded in this editing session.</div> : <div className="mediaGrid">{manager.media.map((item) => <article key={item.id} className="mediaItem"><img src={item.previewSource} alt={item.altText} /><div><strong>{item.altText}</strong><small>{item.contentType} · {item.byteSize} bytes</small></div><label>Alt text for {item.altText}<input aria-label={`Alt text for ${item.altText}`} value={altTexts[item.id] ?? item.altText} onChange={(event) => setAltTexts({ ...altTexts, [item.id]: event.target.value })} /></label><label>Sort order for {item.altText}<input aria-label={`Sort order for ${item.altText}`} inputMode="numeric" value={orders[item.id] ?? String(item.sortOrder)} onChange={(event) => setOrders({ ...orders, [item.id]: event.target.value })} /></label><div className="mediaActions"><button className="secondaryButton" type="button" onClick={() => void saveAltText(item)}>Save alt text</button><button className="secondaryButton" type="button" onClick={() => void saveOrder(item)}>Save media order</button><button className="secondaryButton" type="button" onClick={() => void manager.update(item.id, { isPrimary: true })}><Star size={14} /> {item.isPrimary ? "Primary" : "Make primary"}</button><button className="secondaryButton" type="button" aria-label={`Delete ${item.altText}`} onClick={() => setDeleteTarget(item)}><Trash2 size={14} /></button></div></article>)}</div>}{deleteTarget && <div className="inlineConfirm"><p>Delete this image permanently?</p><button className="secondaryButton" type="button" onClick={() => setDeleteTarget(undefined)}>Cancel</button><button className="dangerButton" type="button" onClick={() => void manager.remove(deleteTarget.id).then(() => setDeleteTarget(undefined))}>Delete</button></div>}</div>;
}
