// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0

import { Archive } from "lucide-react";
import { useState, type FormEvent } from "react";
import type { CatalogApi } from "../api/catalog-api";
import { useVariantEditor } from "../hooks/use-variant-editor";
import type { ProductVariant } from "../types/catalog.types";
import { PriceEditor } from "./price-editor";

export function VariantEditor({ api, productId }: { readonly api: CatalogApi; readonly productId: string }) {
  const editor = useVariantEditor(api, productId); const [sku, setSku] = useState(""); const [title, setTitle] = useState(""); const [optionName, setOptionName] = useState(""); const [optionValue, setOptionValue] = useState(""); const [validation, setValidation] = useState<string>(); const [archiveTarget, setArchiveTarget] = useState<ProductVariant>();
  const normalizedSku = sku.trim().replace(/\s+/g, " ").toUpperCase();
  async function submit(event: FormEvent) { event.preventDefault(); if (!normalizedSku || !title.trim() || !optionName.trim() || !optionValue.trim()) { setValidation("SKU, title, and one option are required."); return; } setValidation(undefined); await editor.create({ sku: normalizedSku, title: title.trim(), optionValues: { [optionName.trim()]: optionValue.trim() } }); }
  return <div className="editorPanel"><form className="variantCreate" onSubmit={(event) => void submit(event)}><div className="formGrid"><label>SKU<input value={sku} onChange={(event) => setSku(event.target.value)} /></label><label>Variant title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Option name 1<input aria-label="Option name 1" value={optionName} onChange={(event) => setOptionName(event.target.value)} /></label><label>Option value 1<input aria-label="Option value 1" value={optionValue} onChange={(event) => setOptionValue(event.target.value)} /></label></div><p className="skuPreview">Normalized SKU: <strong>{normalizedSku || "—"}</strong></p>{validation && <p className="formError">{validation}</p>}{editor.notice && <p className="formError">{editor.notice}</p>}<button className="primaryButton" type="submit">Add variant</button></form><div className="variantList">{editor.variants.length === 0 ? <div className="emptyState">No variants added in this editing session.</div> : editor.variants.map((variant) => <section key={variant.id} className="variantRow"><header><div><strong>{variant.title}</strong><small>{variant.sku} · {Object.entries(variant.optionValues).map(([key, value]) => `${key}: ${value}`).join(", ")}</small></div><button type="button" aria-label={`Archive ${variant.sku}`} onClick={() => setArchiveTarget(variant)}><Archive size={15} /></button></header><PriceEditor variant={variant} currentPrice={editor.prices[variant.id]} onReplace={(amount) => editor.replacePrice(variant.id, amount)} /></section>)}</div>{archiveTarget && <div className="inlineConfirm"><p>Archive this variant?</p><button className="secondaryButton" onClick={() => setArchiveTarget(undefined)}>Cancel</button><button className="dangerButton" onClick={() => void editor.archive(archiveTarget).then(() => setArchiveTarget(undefined))}>Archive</button></div>}</div>;
}
