// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0
import { randomBytes } from "node:crypto"; import type { RequestHandler } from "express"; import type { CustomerAuthenticationServiceContract } from "../../application/services/interfaces/customer-authentication.service"; import type { CustomerSessionServiceContract } from "../../application/services/interfaces/customer-session.service"; import { successResponse } from "../../../../shared/http/api-response"; import { parseBody,googleSchema } from "../validators/customer.validator"; import { clearCookie,readCookie,setCsrfCookie,setSessionCookie,type StorefrontCookieConfig } from "../middleware/storefront-cookies";
export class CustomerAuthController { constructor(private readonly auth:CustomerAuthenticationServiceContract,private readonly sessions:CustomerSessionServiceContract,private readonly cookies:StorefrontCookieConfig){}
 guest:RequestHandler=async(_req,res,next)=>{try{const x=await this.sessions.createGuest();setSessionCookie(res,this.cookies.guestName,x.rawToken,x.principal.expiresAt,this.cookies);this.csrf(res);res.status(201).json(successResponse("Guest session created",{kind:"guest",expiresAt:x.principal.expiresAt}));}catch(e){next(e);}};
 google:RequestHandler=async(req,res,next)=>{try{const x=await this.auth.loginWithGoogle(parseBody(googleSchema,req.body).credential);setSessionCookie(res,this.cookies.customerName,x.rawToken,x.principal.expiresAt,this.cookies);this.csrf(res);res.json(successResponse("Customer signed in",{kind:"customer",customerId:x.principal.customerId,email:x.principal.email,expiresAt:x.principal.expiresAt}));}catch(e){next(e);}};
 session:RequestHandler=async(req,res,next)=>{try{const customer=readCookie(req,this.cookies.customerName);if(customer!==undefined){const x=await this.sessions.resolveCustomer(customer,true);setSessionCookie(res,this.cookies.customerName,x.rawToken,x.principal.expiresAt,this.cookies);this.csrf(res);res.json(successResponse("Customer session restored",{kind:"customer",customerId:x.principal.customerId,email:x.principal.email,expiresAt:x.principal.expiresAt}));return;}const guest=readCookie(req,this.cookies.guestName);if(guest!==undefined){const x=await this.sessions.resolveGuest(guest);this.csrf(res);res.json(successResponse("Guest session restored",{kind:"guest",expiresAt:x.expiresAt}));return;}res.json(successResponse("Anonymous session",{kind:"anonymous"}));}catch(e){next(e);}};
 logout:RequestHandler=async(req,res,next)=>{try{const raw=readCookie(req,this.cookies.customerName);if(raw!==undefined)await this.auth.logout(raw);clearCookie(res,this.cookies.customerName,this.cookies);clearCookie(res,this.cookies.csrfName,this.cookies);res.json(successResponse("Customer signed out",{}));}catch(e){next(e);}};
 private csrf(res:Parameters<RequestHandler>[1]){setCsrfCookie(res,randomBytes(24).toString("base64url"),this.cookies);}
}
