// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0
import type { DatabaseSession } from "../../../../../shared/database/transaction";
import type { SupportTicket, TicketStatus } from "../../../domain/entities/support-ticket";
import type { TicketMessage } from "../../../domain/entities/ticket-message";
import type { SupportEvent, SupportRepository } from "../../../application/repositories/interfaces/support.repository";
export class PostgresqlSupportRepository implements SupportRepository {
 async create(s:DatabaseSession,t:SupportTicket){await s.query(`INSERT INTO support_tickets(id,customer_id,order_id,subject,description,priority,status,version,created_by_id,assignee_id,sla_paused_seconds,sla_stopped_seconds,sla_pause_started_at,sla_stopped_at,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,[t.id,t.customerId,t.orderId??null,t.subject,t.description,t.priority,t.status,t.version,t.createdById,t.assigneeId??null,t.slaPausedSeconds,t.slaStoppedSeconds,t.slaPauseStartedAt??null,t.slaStoppedAt??null,t.createdAt,t.updatedAt]);}
 async find(s:DatabaseSession,id:string,lock=false){const r=await s.query<Row>(`SELECT * FROM support_tickets WHERE id=$1${lock?" FOR UPDATE":""}`,[id]);return r.rows[0]===undefined?undefined:ticket(r.rows[0]);}
 async list(s:DatabaseSession,q:{page:number;pageSize:number;createdById?:string}){const where=q.createdById===undefined?"":"WHERE created_by_id=$1";const vals=q.createdById===undefined?[q.pageSize,(q.page-1)*q.pageSize]:[q.createdById,q.pageSize,(q.page-1)*q.pageSize];const n=q.createdById===undefined?0:1;const r=await s.query<Row & {total:string}>(`SELECT *,count(*) OVER()::text total FROM support_tickets ${where} ORDER BY created_at DESC,id DESC LIMIT $${n+1} OFFSET $${n+2}`,vals);return {items:r.rows.map(ticket),totalItems:Number(r.rows[0]?.total??0)};}
 async update(s:DatabaseSession,t:SupportTicket,v:number){const r=await s.query(`UPDATE support_tickets SET status=$3,version=$4,assignee_id=$5,sla_paused_seconds=$6,sla_stopped_seconds=$7,sla_pause_started_at=$8,sla_stopped_at=$9,closed_at=$10,updated_at=$11 WHERE id=$1 AND version=$2`,[t.id,v,t.status,t.version,t.assigneeId??null,t.slaPausedSeconds,t.slaStoppedSeconds,t.slaPauseStartedAt??null,t.slaStoppedAt??null,t.status==="closed"?t.updatedAt:null,t.updatedAt]);return r.rowCount===1;}
 async appendEvent(s:DatabaseSession,e:SupportEvent){const r=await s.query(`INSERT INTO support_ticket_events(id,ticket_id,actor_id,from_status,to_status,source,idempotency_key,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(idempotency_key) DO NOTHING`,[e.id,e.ticketId,e.actorId,e.fromStatus,e.toStatus,e.source,e.idempotencyKey,e.occurredAt]);return r.rowCount===1;}
 async findEventByKey(s:DatabaseSession,key:string){const r=await s.query<Row>("SELECT * FROM support_ticket_events WHERE idempotency_key=$1",[key]);return r.rows[0]===undefined?undefined:event(r.rows[0]);}
 async appendMessage(s:DatabaseSession,m:TicketMessage){await s.query("INSERT INTO support_ticket_messages(id,ticket_id,author_id,body,created_at) VALUES($1,$2,$3,$4,$5)",[m.id,m.ticketId,m.authorId,m.body,m.createdAt]);}
 async listMessages(s:DatabaseSession,id:string){const r=await s.query<Row>("SELECT * FROM support_ticket_messages WHERE ticket_id=$1 ORDER BY created_at,id",[id]);return r.rows.map(x=>({id:String(x.id),ticketId:String(x.ticket_id),authorId:String(x.author_id),body:String(x.body),createdAt:iso(x.created_at)}));}
 async listEvents(s:DatabaseSession,id:string){const r=await s.query<Row>("SELECT * FROM support_ticket_events WHERE ticket_id=$1 ORDER BY occurred_at,id",[id]);return r.rows.map(event);}
 async appendAudit(s:DatabaseSession,e:Parameters<SupportRepository["appendAudit"]>[1]){await s.query("INSERT INTO support_audit_events(id,ticket_id,actor_id,action,resource_type,resource_id,correlation_id,metadata,occurred_at) VALUES($1,$2,$3,$4,'support_ticket',$5,$6,$7::jsonb,$8)",[e.id,e.ticketId,e.actorId,e.action,e.resourceId,e.correlationId,JSON.stringify(e.metadata),e.occurredAt]);}
 async appendDeniedAudit(s:DatabaseSession,e:Parameters<SupportRepository["appendDeniedAudit"]>[1]){await s.query("INSERT INTO audit_events(id,actor_type,actor_id,action,resource_type,resource_id,outcome,correlation_id,metadata,occurred_at) VALUES($1,'user',$2,$3,'support',$4,'denied',$5,'{}'::jsonb,$6)",[e.id,e.actorId,e.action,e.resourceId,e.correlationId,e.occurredAt]);}
 async claimBreached(s:DatabaseSession,now:string,limit:number){const r=await s.query<Row>(`SELECT * FROM support_tickets WHERE status NOT IN ('resolved','closed','escalated') AND created_at + (CASE priority WHEN 'urgent' THEN interval '2 hours' WHEN 'high' THEN interval '8 hours' WHEN 'normal' THEN interval '24 hours' ELSE interval '72 hours' END) + make_interval(secs => sla_paused_seconds + sla_stopped_seconds) <= $1 ORDER BY created_at,id FOR UPDATE SKIP LOCKED LIMIT $2`,[now,limit]);return r.rows.map(ticket);}
 async countSummary(s:DatabaseSession,asOf:string,start:string,end:string){const r=await s.query<{open:string;breaches:string}>(`SELECT count(*) FILTER(WHERE status NOT IN ('resolved','closed'))::text open,count(*) FILTER(WHERE status='escalated' AND updated_at >= $2 AND updated_at < $3)::text breaches FROM support_tickets WHERE created_at <= $1`,[asOf,start,end]);return {openTickets:Number(r.rows[0]?.open??0),slaBreaches:Number(r.rows[0]?.breaches??0)};}
}
type Row=Record<string,unknown>; const iso=(v:unknown)=>(v instanceof Date?v:new Date(String(v))).toISOString();
function ticket(r:Row):SupportTicket{return {id:String(r.id),customerId:String(r.customer_id),...(r.order_id==null?{}:{orderId:String(r.order_id)}),subject:String(r.subject),description:String(r.description),priority:r.priority as SupportTicket["priority"],status:r.status as TicketStatus,version:Number(r.version),createdById:String(r.created_by_id),...(r.assignee_id==null?{}:{assigneeId:String(r.assignee_id)}),slaPausedSeconds:Number(r.sla_paused_seconds),slaStoppedSeconds:Number(r.sla_stopped_seconds),...(r.sla_pause_started_at==null?{}:{slaPauseStartedAt:iso(r.sla_pause_started_at)}),...(r.sla_stopped_at==null?{}:{slaStoppedAt:iso(r.sla_stopped_at)}),createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)};}
function event(r:Row):SupportEvent{return {id:String(r.id),ticketId:String(r.ticket_id),actorId:String(r.actor_id),fromStatus:r.from_status as TicketStatus,toStatus:r.to_status as TicketStatus,source:r.source as "manual"|"automatic",idempotencyKey:String(r.idempotency_key),occurredAt:iso(r.occurred_at)};}
