// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0
import type { DatabaseSession } from "../../../../../shared/database/transaction"; import type { Customer } from "../../../domain/entities/customer"; import type { CustomerSession } from "../../../domain/entities/customer-session"; import type { GuestSession } from "../../../domain/entities/guest-session"; import type { CustomerAddress } from "../../../domain/entities/customer-address";
export interface ExternalIdentityRecord { readonly id: string; readonly customerId: string; readonly provider: "google"; readonly providerSubject: string; readonly providerEmail: string }
export interface CustomerRepository {
  findCustomerById(s: DatabaseSession, id: string): Promise<Customer | undefined>; findCustomerByEmail(s: DatabaseSession, email: string): Promise<Customer | undefined>; findIdentity(s: DatabaseSession, provider: "google", subject: string): Promise<ExternalIdentityRecord | undefined>;
  createCustomer(s: DatabaseSession, customer: Customer): Promise<void>; createIdentity(s: DatabaseSession, identity: ExternalIdentityRecord, now: string): Promise<void>; touchIdentity(s: DatabaseSession, identityId: string, email: string, now: string): Promise<void>;
  createCustomerSession(s: DatabaseSession, session: CustomerSession): Promise<void>; findCustomerSessionByHash(s: DatabaseSession, hash: string, lock?: boolean): Promise<CustomerSession | undefined>; replaceCustomerSession(s: DatabaseSession, session: CustomerSession): Promise<void>; revokeCustomerSession(s: DatabaseSession, id: string, now: string): Promise<void>;
  createGuestSession(s: DatabaseSession, session: GuestSession): Promise<void>; findGuestSessionByHash(s: DatabaseSession, hash: string): Promise<GuestSession | undefined>;
  updateCustomer(s: DatabaseSession, customer: Customer, expectedVersion: number): Promise<boolean>; listAddresses(s: DatabaseSession, customerId: string): Promise<readonly CustomerAddress[]>; findAddress(s: DatabaseSession, customerId: string, addressId: string): Promise<CustomerAddress | undefined>; createAddress(s: DatabaseSession, address: CustomerAddress): Promise<void>; updateAddress(s: DatabaseSession, address: CustomerAddress, expectedVersion: number): Promise<boolean>; deleteAddress(s: DatabaseSession, customerId: string, addressId: string): Promise<boolean>; setDefaultAddress(s: DatabaseSession, customerId: string, addressId: string, now: string): Promise<boolean>;
}
