// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0

import type { ZodType } from "zod";
import { mapCustomer360, mapFollowup } from "../mappers/crm.mapper";
import { customer360EnvelopeSchema, errorEnvelopeSchema, followupEnvelopeSchema, noteEnvelopeSchema } from "../schemas/crm-api.schema";
import type { Customer360View, CrmNoteView, FollowupUpdateInput, FollowupView } from "../types/crm.types";

export type CrmErrorCode="UNAUTHORIZED"|"FORBIDDEN"|"CUSTOMER_NOT_FOUND"|"STALE_VERSION"|"VALIDATION_ERROR"|"INVALID_RESPONSE"|"UNAVAILABLE";
export class CrmApiError extends Error{ constructor(readonly code:CrmErrorCode,message:string){ super(message); this.name="CrmApiError"; } }
export interface CrmOperationsApi{ getCustomer(customerId:string,signal?:AbortSignal):Promise<Customer360View>; createNote(customerId:string,input:{body:string;correctsNoteId?:string}):Promise<CrmNoteView>; createFollowup(customerId:string,input:{dueAt:string;description:string}):Promise<FollowupView>; updateFollowup(customerId:string,followupId:string,input:FollowupUpdateInput):Promise<FollowupView>; }
export function createCrmOperationsApi(baseUrl:string,accessToken:string):CrmOperationsApi{ const request=createRequest(baseUrl,accessToken); return { async getCustomer(id,signal){ return mapCustomer360(parse(customer360EnvelopeSchema,await request(`/v1/admin/customers/${id}`,{signal})).data as Customer360View); }, async createNote(id,input){ return parse(noteEnvelopeSchema,await request(`/v1/admin/customers/${id}/notes`,{method:"POST",body:JSON.stringify(input)})).data as CrmNoteView; }, async createFollowup(id,input){ return mapFollowup(parse(followupEnvelopeSchema,await request(`/v1/admin/customers/${id}/followups`,{method:"POST",body:JSON.stringify(input)})).data as FollowupView); }, async updateFollowup(id,followupId,input){ return mapFollowup(parse(followupEnvelopeSchema,await request(`/v1/admin/customers/${id}/followups/${followupId}`,{method:"PATCH",body:JSON.stringify(input)})).data as FollowupView); } }; }
function createRequest(baseUrl:string,accessToken:string){ return async(path:string,init?:RequestInit):Promise<unknown>=>{ let response:Response; try{ response=await fetch(`${baseUrl}${path}`,{...init,headers:{"content-type":"application/json",authorization:`Bearer ${accessToken}`,"x-correlation-id":crypto.randomUUID(),...init?.headers}}); }catch(error){ if(error instanceof DOMException&&error.name==="AbortError")throw error; throw new CrmApiError("UNAVAILABLE","CRM service is unavailable."); } const body:unknown=await response.json().catch(()=>undefined); if(!response.ok){ const parsed=errorEnvelopeSchema.safeParse(body); const code=parsed.success?normalize(parsed.data.errorCode):"UNAVAILABLE"; throw new CrmApiError(code,message(code)); } return body; }; }
function parse<T>(schema:ZodType<T>,value:unknown):T{ const parsed=schema.safeParse(value); if(!parsed.success)throw new CrmApiError("INVALID_RESPONSE","Invalid CRM response."); return parsed.data; }
function normalize(code:string):CrmErrorCode{ return ["UNAUTHORIZED","FORBIDDEN","CUSTOMER_NOT_FOUND","STALE_VERSION","VALIDATION_ERROR"].includes(code)?code as CrmErrorCode:"UNAVAILABLE"; }
function message(code:CrmErrorCode):string{ if(code==="FORBIDDEN")return "Permission denied."; if(code==="CUSTOMER_NOT_FOUND")return "Customer was not found."; if(code==="STALE_VERSION")return "Refresh required."; return "CRM request could not be completed."; }
