// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0
import type { DatabaseSession } from "../../../../../shared/database/transaction";
import type { SupportTicket, TicketStatus } from "../../../domain/entities/support-ticket";
import type { TicketMessage } from "../../../domain/entities/ticket-message";
import type { SupportAttachment } from "../../../domain/entities/support-attachment";
export interface SupportEvent { readonly id:string;readonly ticketId:string;readonly actorId:string;readonly fromStatus:TicketStatus;readonly toStatus:TicketStatus;readonly source:"manual"|"automatic";readonly idempotencyKey:string;readonly occurredAt:string; }
export interface BreachedSupportTicket { readonly ticket: SupportTicket; readonly breachAt: string; }
export interface ClaimedSupportAttachment { readonly id:string;readonly ticketId:string;readonly objectKey:string;readonly version:number; }
export interface SupportRepository { create(session:DatabaseSession,ticket:SupportTicket):Promise<void>; find(session:DatabaseSession,id:string,lock?:boolean):Promise<SupportTicket|undefined>; list(session:DatabaseSession, query:{page:number;pageSize:number;createdById?:string;availableOrAssigneeId?:string}):Promise<{items:readonly SupportTicket[];totalItems:number}>; update(session:DatabaseSession,ticket:SupportTicket,expectedVersion:number):Promise<boolean>; appendEvent(session:DatabaseSession,event:SupportEvent):Promise<boolean>; findEventByKey(session:DatabaseSession,ticketId:string,key:string):Promise<SupportEvent|undefined>; appendMessage(session:DatabaseSession,message:TicketMessage):Promise<void>; listMessages(session:DatabaseSession,ticketId:string):Promise<readonly TicketMessage[]>; listEvents(session:DatabaseSession,ticketId:string):Promise<readonly SupportEvent[]>; createAttachment(session:DatabaseSession,attachment:SupportAttachment):Promise<void>; findAttachment(session:DatabaseSession,ticketId:string,attachmentId:string):Promise<SupportAttachment|undefined>; countRetainedAttachments(session:DatabaseSession,ticketId:string):Promise<{count:number;bytes:number}>; claimAttachmentsForScan(session:DatabaseSession,now:string,limit:number):Promise<readonly ClaimedSupportAttachment[]>; markAttachmentClean(session:DatabaseSession,attachmentId:string,expectedVersion:number,at:string):Promise<boolean>; markAttachmentRejected(session:DatabaseSession,attachmentId:string,expectedVersion:number,at:string):Promise<boolean>; claimAttachmentsForRetention(session:DatabaseSession,now:string,limit:number):Promise<readonly ClaimedSupportAttachment[]>; markAttachmentDeleted(session:DatabaseSession,attachmentId:string,expectedVersion:number,at:string):Promise<boolean>; appendAudit(session:DatabaseSession,entry:{id:string;ticketId:string;actorId:string;action:string;resourceId:string;correlationId:string;metadata:object;occurredAt:string}):Promise<void>; claimBreached(session:DatabaseSession,now:string,limit:number):Promise<readonly BreachedSupportTicket[]>; countSummary(session:DatabaseSession,asOf:string,start:string,end:string):Promise<{openTickets:number;slaBreaches:number}>; appendDeniedAudit(session:DatabaseSession,entry:{id:string;actorId:string;action:string;resourceId:string;correlationId:string;occurredAt:string}):Promise<void>; }
