# SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
# SPDX-License-Identifier: Apache-2.0

limit.maxIDLength:
  - value: 255
    constraints: {}

# Development only: make newly registered search attributes visible immediately.
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
    constraints: {}
