// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0

import { useState } from "react";
import { useParams } from "react-router-dom";
import type { StaffRole } from "../../authentication/api/oidc-manager";
import type { SupportOperationsApi } from "../api/support-api";
import { AttachmentPanel } from "../components/attachment-panel";
import { TicketContext } from "../components/ticket-context";
import { TicketTimeline } from "../components/ticket-timeline";
import { useSupportTicket } from "../hooks/use-support-ticket";
import type { SupportAttachmentView, TicketStatus } from "../types/support.types";

export function TicketDetailPage({api,roles}:{readonly api:SupportOperationsApi;readonly roles:readonly StaffRole[]}){ const {ticketId}=useParams(); const {data,error,loading,reload,replace}=useSupportTicket(api,ticketId); const [mutationError,setMutationError]=useState<string>(); const [status,setStatus]=useState<string>(); const [lastStatus,setLastStatus]=useState<TicketStatus>(); const transition=async(target:TicketStatus)=>{if(!data)return;setMutationError(undefined);setStatus(undefined);setLastStatus(target);try{const updated=await api.update(data.ticket.id,{status:target,version:data.ticket.version,idempotencyKey:`support-transition:${data.ticket.id}:${target}:${data.ticket.version}`});replace({...data,ticket:updated});setStatus("Ticket updated");}catch(reason){setMutationError(reason instanceof Error?reason.message:"Ticket could not be updated.");}}; const upload=async(file:File)=>{if(!data)return;const attachment=await api.uploadAttachment(data.ticket.id,file);replace({...data,attachments:[...data.attachments,attachment]});}; const download=async(attachment:SupportAttachmentView)=>{if(!data)return;const blob=await api.downloadAttachment(data.ticket.id,attachment.id);const url=URL.createObjectURL(blob);URL.revokeObjectURL(url);}; if(loading&&!data)return <section className="pageState" role="status">Loading support ticket…</section>; if(error)return <section className="pageState" role="alert"><h1>{error}</h1><button className="secondaryButton" type="button" onClick={reload}>Retry</button></section>; if(!data)return null; return <section className="catalogWorkspace operationsWorkspace supportWorkspace customerWorkspace"><header className="workspaceHeader splitHeader"><div><p className="sectionKicker">Support ticket</p><h1>{data.ticket.subject}</h1><p>{data.ticket.status} · version {data.ticket.version}</p></div></header>{mutationError?<div className="pageState" role="alert"><p>{mutationError}</p><button className="secondaryButton" type="button" onClick={()=>lastStatus&&void transition(lastStatus)}>Retry update</button></div>:null}{status?<div className="pageState" role="status">{status}</div>:null}<div className="actionBar">{data.ticket.status==="assigned"?<button className="primaryButton" type="button" onClick={()=>void transition("in_progress")}>Start progress</button>:null}{data.ticket.status==="in_progress"?<button className="secondaryButton" type="button" onClick={()=>void transition("waiting_customer")}>Wait for customer</button>:null}{data.ticket.status!=="closed"?<button className="secondaryButton" type="button" onClick={()=>void transition("escalated")}>Escalate manually</button>:null}</div><div className="detailGrid"><TicketContext detail={data}/><AttachmentPanel attachments={data.attachments} onUpload={file=>void upload(file)} onDownload={attachment=>void download(attachment)}/><TicketTimeline detail={data}/></div></section>; }
