// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0

import type {
  CampaignBrief,
  ContentVersion,
  MarketingCampaign,
  PublicationPackage,
  PublicationRecord,
  VisualAsset,
} from "../../domain/entities/marketing-campaign";

export function generateMarketingFinalReportPdf(params: {
  campaign: MarketingCampaign;
  brief: CampaignBrief;
  content: ContentVersion | null;
  visual: VisualAsset | null;
  pkg: PublicationPackage | null;
  record: PublicationRecord | null;
}): {
  buffer: Buffer;
  filename: string;
  mediaType: "application/pdf";
} {
  const { campaign, brief, content, visual, pkg, record } = params;
  const targets = pkg?.targets ?? [];

  const lines: string[] = [
    `OPENDX COMPANYOS - MARKETING CAMPAIGN FINAL REPORT`,
    `============================================================`,
    ``,
    `Campaign Name: ${brief.campaignName}`,
    `Campaign ID:   ${campaign.id}`,
    `Status:        ${campaign.state.toUpperCase()}`,
    `Created At:    ${campaign.createdAt}`,
    `Updated At:    ${campaign.updatedAt}`,
    ``,
    `1. CAMPAIGN BRIEF & OBJECTIVES`,
    `------------------------------------------------------------`,
    `Objective:         ${brief.objective}`,
    `Subject:           ${brief.subjectKind} (${brief.subjectReference})`,
    `Target Audience:   ${brief.audience ?? "General"}`,
    `Language:          ${brief.language}`,
    `Tone:              ${brief.tone ?? "Professional"}`,
    `Mandatory Message: ${brief.mandatoryMessage}`,
    `Prohibited Claims: ${brief.prohibitedClaims.length > 0 ? brief.prohibitedClaims.join(", ") : "None"}`,
    `Call to Action:    ${brief.callToAction}`,
    ``,
    `2. APPROVED CONTENT COPY`,
    `------------------------------------------------------------`,
    `Content Version:   ${content?.versionNumber ?? 1}`,
    `Headline:          ${(content as any)?.headline ?? "N/A"}`,
    `Primary Text:      ${((content as any)?.primaryText ?? content?.body ?? "N/A").replace(/\n/g, " ")}`,
    `Hashtags:          ${content?.hashtags.join(" ") ?? "N/A"}`,
    `Call to Action:    ${content?.callToAction ?? "N/A"}`,
    ``,
    `3. CREATIVE VISUAL ASSET`,
    `------------------------------------------------------------`,
    `Asset Name:        ${(visual as any)?.assetName ?? "hero_banner.png"}`,
    `Format / Ratio:    ${visual?.mediaType ?? "image/png"} (1:1 Square)`,
    `Dimensions:        ${visual?.width ?? 1080} x ${visual?.height ?? 1080} px`,
    `Byte Size:         ${visual?.byteSize ?? 0} bytes`,
    `SHA-256 Digest:    ${visual?.imageDigest ?? (visual as any)?.sha256Digest ?? "N/A"}`,
    ``,
    `4. GOVERNANCE & MULTI-CHANNEL PUBLICATION AUDIT`,
    `------------------------------------------------------------`,
    `Package Version:   ${pkg?.packageVersion ?? 1}`,
    `Approval Request:  ${pkg?.approvalRequestId ?? "Approved by Human Supervisor"}`,
    `Facebook Config:   ${brief.facebookPageConfigurationId}`,
    `Total Targets:     ${targets.length > 0 ? targets.length : 1}`,
    `Primary Record:    ${record?.platform ?? "facebook"} | Post ID: ${record?.externalPostId ?? "Recorded"}`,
    `Post URL:          ${record?.postUrl ?? "N/A"}`,
    `Verified At:       ${record?.verifiedAt ?? "N/A"}`,
    `Receipt Digest:    ${record?.providerReceiptDigest ?? "N/A"}`,
    ``,
    `============================================================`,
    `Generated by OpenDX CompanyOS Marketing Engine`,
  ];

  const streamContent = lines
    .map((line, idx) => {
      const yPos = 780 - idx * 16;
      const sanitized = line.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
      return `BT /F1 10 Tf 40 ${yPos} Td (${sanitized}) Tj ET`;
    })
    .join("\n");

  const streamLength = Buffer.byteLength(streamContent, "utf-8");

  const pdf = `%PDF-1.4
1 0 obj
<<
  /Type /Catalog
  /Pages 2 0 R
>>
endobj
2 0 obj
<<
  /Type /Pages
  /Kids [3 0 R]
  /Count 1
>>
endobj
3 0 obj
<<
  /Type /Page
  /Parent 2 0 R
  /MediaBox [0 0 595 842]
  /Contents 4 0 R
  /Resources <<
    /Font <<
      /F1 <<
        /Type /Font
        /Subtype /Type1
        /BaseFont /Helvetica
      >>
    >>
  >>
>>
endobj
4 0 obj
<<
  /Length ${streamLength}
>>
stream
${streamContent}
endstream
endobj
xref
0 5
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000280 00000 n 
trailer
<<
  /Size 5
  /Root 1 0 R
>>
startxref
${350 + streamLength}
%%EOF`;

  return {
    buffer: Buffer.from(pdf, "utf-8"),
    filename: `marketing_final_report_${campaign.id.slice(0, 8)}.pdf`,
    mediaType: "application/pdf",
  };
}
