// SPDX-FileCopyrightText: 2026 OpenDX CompanyOS contributors
// SPDX-License-Identifier: Apache-2.0

import type { AgenticApprovalDetail as Detail, AgenticApprovalDecision } from "../types/agentic.types";
export function ApprovalDetail({ detail, canDecide, onDecision }: { readonly detail: Detail; readonly canDecide: boolean; readonly onDecision: (decision: AgenticApprovalDecision["decision"]) => void }) {
  const expired = detail.approval.state === "pending" && Date.parse(detail.approval.expiresAt) <= Date.now();
  return <section className="agenticApprovalDetail"><header><h2>Approval evidence</h2><span>{expired ? "Expired" : detail.approval.state}</span></header><dl className="metricList"><div><dt>Requester</dt><dd>{detail.approval.requesterId}</dd></div><div><dt>Resource</dt><dd>{detail.approval.resourceType} · {detail.approval.resourceId}</dd></div><div><dt>Action</dt><dd>{detail.approval.action}</dd></div><div><dt>Parameters digest</dt><dd>{detail.approval.parametersDigest}</dd></div>{detail.payloadDigest && <div><dt>Workflow payload digest</dt><dd>{detail.payloadDigest}</dd></div>}<div><dt>Policy version</dt><dd>{detail.approval.policyVersion}</dd></div><div><dt>Approval version</dt><dd>{detail.approval.version}</dd></div><div><dt>Expiry</dt><dd>{detail.approval.expiresAt}</dd></div><div><dt>Risk</dt><dd><strong>{title(detail.risk.level)} risk</strong> · {detail.risk.basis}</dd></div><div><dt>Expected effect</dt><dd>{detail.expectedEffect}</dd></div></dl><h3>Sources</h3>{detail.sources.length === 0 ? <p>No task sources are bound.</p> : <ul>{detail.sources.map((source) => <li key={`${source.sourceType}:${source.sourceId}`}>{source.sourceType} · {source.sourceId} · {source.sourceDigest}</li>)}</ul>}{canDecide && !expired && detail.approval.state === "pending" && <div className="dialogActions"><button type="button" onClick={() => onDecision("revision_requested")}>Request revision</button><button className="dangerButton" type="button" onClick={() => onDecision("rejected")}>Reject</button><button className="primaryButton" type="button" onClick={() => onDecision("approved")}>Approve</button></div>}</section>;
}
function title(value: string): string { return `${value.charAt(0).toUpperCase()}${value.slice(1)}`; }
